### PR TITLE
feat: add doc search

### PR DESCRIPTION
**Pull request by urfreespace**

### CODE REVIEW

**Comment by urfreespace** [comment]
When running our DocSearch crawler, it is required to set the appId configuration key to your own Application ID. Now we left unset, the appId will fallback to the one used with the free, hosted version of Algolia DocSearch. @tuteng

**Comment by tuteng** [comment]
Please check build @urfreespace

**Comment by urfreespace** [comment]
> Please check build @urfreespace

fixed, PTAL, thanks @tuteng

**Comment by tuteng** [comment]
We wait until a document search is available before merging this pr @urfreespace

**Comment by urfreespace** [comment]
> We wait until a document search is available before merging this pr @urfreespace

Each search account is bound to the domain name, and it is not sure whether the search capability of the preview page will crawl the page @tuteng

**Comment by urfreespace** [comment]
image

@tuteng PTAL again

**Review by tuteng — APPROVED** [review]

**Pull request merged**
