### PR TITLE
Corrected trace log level as not being supported by Python

### PR DESCRIPTION
**Pull request by htbmw**
Python does not support the "trace" log level:

https://docs.python.org/3/library/logging.html#levels
https://www.logicmonitor.com/blog/python-logging-levels-explained

### CODE REVIEW

**Review by Huanli-Meng — APPROVED** [review]

**Comment by Huanli-Meng** [comment]
@htbmw Thanks for updating the doc. I noticed only release v0.13.0 is updated. Could you please also update docs for releases v0.14.0 and the latest release?

Latest: https://github.com/streamnative/function-mesh-website/blob/main/docs/reference/crd-config/function-crd.md?plain=1#L294

Release v0.14.0: https://github.com/streamnative/function-mesh-website/blob/main/versioned_docs/version-0.14.0/reference/crd-config/function-crd.md?plain=1#L294

Many thanks

**Comment by htbmw** [comment]
@Huanli-Meng Thanks for the approval.
I didn't realize there were versioned docs.
I chose the Edit function directly from the site where the docs are displayed, so it must have been showing me the version 0.13.0 docs without me realizing this.

I will make fixes to the other versioned docs and the master branch (current version) as well.

**Comment by htbmw** [comment]
@Huanli-Meng 
Requested files updated.

**Comment by Huanli-Meng** [comment]
@nlu90 @freeznet @jiangpengcheng could any of you help review the PR as a code owner? Thanks.

**Review by nlu90 — APPROVED** [review]

**Comment by nlu90** [comment]
@htbmw Thank you very much for the contribution!

**Pull request merged**
